// 60+ sample activities, categorized
export const ACTIVITIES = [
  { id: 'a1', name: 'Brunch at Café', category: 'Food', icon: '🥐', defaultDuration: 90, defaultMood: 'relaxed' },
  { id: 'a2', name: 'Hiking Trail', category: 'Outdoor', icon: '🥾', defaultDuration: 180, defaultMood: 'energetic' },
  { id: 'a3', name: 'Movie Night', category: 'Entertainment', icon: '🎬', defaultDuration: 120, defaultMood: 'happy' },
  { id: 'a4', name: 'Reading Session', category: 'Quiet', icon: '📚', defaultDuration: 60, defaultMood: 'calm' },
  { id: 'a5', name: 'Visit Museum', category: 'Culture', icon: '🏛️', defaultDuration: 90, defaultMood: 'curious' },
  { id: 'a6', name: 'Board Games', category: 'Entertainment', icon: '🎲', defaultDuration: 120, defaultMood: 'social' },
  { id: 'a7', name: 'Morning Run', category: 'Fitness', icon: '🏃', defaultDuration: 45, defaultMood: 'energetic' },
  { id: 'a8', name: 'Yoga Class', category: 'Fitness', icon: '🧘', defaultDuration: 60, defaultMood: 'calm' },
  { id: 'a9', name: 'Baking Party', category: 'Food', icon: '🧁', defaultDuration: 120, defaultMood: 'happy' },
  { id: 'a10', name: 'Photography Walk', category: 'Outdoor', icon: '📷', defaultDuration: 120, defaultMood: 'curious' },
  { id: 'a11', name: 'Picnic in Park', category: 'Outdoor', icon: '🧺', defaultDuration: 150, defaultMood: 'relaxed' },
  { id: 'a12', name: 'Karaoke', category: 'Entertainment', icon: '🎤', defaultDuration: 90, defaultMood: 'social' },
  { id: 'a13', name: 'Spa Time', category: 'Self-care', icon: '💆', defaultDuration: 90, defaultMood: 'relaxed' },
  { id: 'a14', name: 'House Clean Sprint', category: 'Home', icon: '🧹', defaultDuration: 60, defaultMood: 'focused' },
  { id: 'a15', name: 'Gardening', category: 'Home', icon: '🌱', defaultDuration: 90, defaultMood: 'calm' },
  { id: 'a16', name: 'Coding Side Project', category: 'Creative', icon: '💻', defaultDuration: 180, defaultMood: 'focused' },
  { id: 'a17', name: 'Art & Painting', category: 'Creative', icon: '🎨', defaultDuration: 120, defaultMood: 'calm' },
  { id: 'a18', name: 'Concert', category: 'Entertainment', icon: '🎟️', defaultDuration: 180, defaultMood: 'happy' },
  { id: 'a19', name: 'Temple Visit', category: 'Culture', icon: '🛕', defaultDuration: 60, defaultMood: 'calm' },
  { id: 'a20', name: 'Cycling', category: 'Fitness', icon: '🚴', defaultDuration: 90, defaultMood: 'energetic' },
  { id: 'a21', name: 'Swimming', category: 'Fitness', icon: '🏊', defaultDuration: 60, defaultMood: 'energetic' },
  { id: 'a22', name: 'Volunteer Work', category: 'Community', icon: '🤝', defaultDuration: 120, defaultMood: 'fulfilling' },
  { id: 'a23', name: 'Farmer’s Market', category: 'Food', icon: '🛒', defaultDuration: 60, defaultMood: 'happy' },
  { id: 'a24', name: 'Road Trip', category: 'Travel', icon: '🚗', defaultDuration: 240, defaultMood: 'adventurous' },
  { id: 'a25', name: 'Beach Day', category: 'Travel', icon: '🏖️', defaultDuration: 240, defaultMood: 'relaxed' },
  { id: 'a26', name: 'Street Food Crawl', category: 'Food', icon: '🌯', defaultDuration: 120, defaultMood: 'social' },
  { id: 'a27', name: 'Coffee with Friends', category: 'Social', icon: '☕', defaultDuration: 60, defaultMood: 'happy' },
  { id: 'a28', name: 'Bookstore Browsing', category: 'Culture', icon: '📚', defaultDuration: 60, defaultMood: 'calm' },
  { id: 'a29', name: 'Stand-up Comedy', category: 'Entertainment', icon: '😂', defaultDuration: 120, defaultMood: 'happy' },
  { id: 'a30', name: 'Mini Golf', category: 'Entertainment', icon: '⛳', defaultDuration: 90, defaultMood: 'fun' },
  { id: 'a31', name: 'Bowling', category: 'Entertainment', icon: '🎳', defaultDuration: 90, defaultMood: 'fun' },
  { id: 'a32', name: 'Skating', category: 'Fitness', icon: '⛸️', defaultDuration: 90, defaultMood: 'energetic' },
  { id: 'a33', name: 'Call Parents', category: 'Family', icon: '📞', defaultDuration: 30, defaultMood: 'warm' },
  { id: 'a34', name: 'Family Lunch', category: 'Family', icon: '🍽️', defaultDuration: 90, defaultMood: 'warm' },
  { id: 'a35', name: 'Temple Prasad', category: 'Culture', icon: '🙏', defaultDuration: 30, defaultMood: 'calm' },
  { id: 'a36', name: 'Explore New Restaurant', category: 'Food', icon: '🍽️', defaultDuration: 90, defaultMood: 'curious' },
  { id: 'a37', name: 'Local Event', category: 'Community', icon: '📣', defaultDuration: 120, defaultMood: 'social' },
  { id: 'a38', name: 'Indoor Climbing', category: 'Fitness', icon: '🧗', defaultDuration: 90, defaultMood: 'energetic' },
  { id: 'a39', name: 'Meditation', category: 'Self-care', icon: '🧘‍♂️', defaultDuration: 20, defaultMood: 'calm' },
  { id: 'a40', name: 'Nap Time', category: 'Self-care', icon: '😴', defaultDuration: 30, defaultMood: 'lazy' },
  { id: 'a41', name: 'Bake Bread', category: 'Food', icon: '🍞', defaultDuration: 120, defaultMood: 'relaxed' },
  { id: 'a42', name: 'DIY Home Project', category: 'Home', icon: '🛠️', defaultDuration: 120, defaultMood: 'focused' },
  { id: 'a43', name: 'Visit Relatives', category: 'Family', icon: '👨‍👩‍👧‍👦', defaultDuration: 120, defaultMood: 'warm' },
  { id: 'a44', name: 'Dog Park', category: 'Outdoor', icon: '🐕', defaultDuration: 60, defaultMood: 'happy' },
  { id: 'a45', name: 'Cat Café', category: 'Entertainment', icon: '🐈', defaultDuration: 60, defaultMood: 'happy' },
  { id: 'a46', name: 'Stargazing', category: 'Outdoor', icon: '🌌', defaultDuration: 90, defaultMood: 'calm' },
  { id: 'a47', name: 'Salsa Night', category: 'Entertainment', icon: '💃', defaultDuration: 120, defaultMood: 'romantic' },
  { id: 'a48', name: 'Poetry Open Mic', category: 'Culture', icon: '🎙️', defaultDuration: 90, defaultMood: 'curious' },
  { id: 'a49', name: 'Anime Binge', category: 'Entertainment', icon: '🍿', defaultDuration: 180, defaultMood: 'happy' },
  { id: 'a50', name: 'Tech Meetup', category: 'Community', icon: '🧑‍💻', defaultDuration: 120, defaultMood: 'curious' },
  { id: 'a51', name: 'Terrarium Build', category: 'Creative', icon: '🪴', defaultDuration: 120, defaultMood: 'calm' },
  { id: 'a52', name: 'Thrifting', category: 'Shopping', icon: '🛍️', defaultDuration: 90, defaultMood: 'curious' },
  { id: 'a53', name: 'Puzzle Time', category: 'Home', icon: '🧩', defaultDuration: 60, defaultMood: 'calm' },
  { id: 'a54', name: 'Language Practice', category: 'Learning', icon: '🗣️', defaultDuration: 60, defaultMood: 'focused' },
  { id: 'a55', name: 'Coding Interview Prep', category: 'Learning', icon: '📈', defaultDuration: 90, defaultMood: 'focused' },
  { id: 'a56', name: 'Cricket with Friends', category: 'Sports', icon: '🏏', defaultDuration: 150, defaultMood: 'energetic' },
  { id: 'a57', name: 'Football Match', category: 'Sports', icon: '⚽', defaultDuration: 120, defaultMood: 'energetic' },
  { id: 'a58', name: 'Tea Tasting', category: 'Food', icon: '🫖', defaultDuration: 60, defaultMood: 'relaxed' },
  { id: 'a59', name: 'Play with Pets', category: 'Home', icon: '🐾', defaultDuration: 45, defaultMood: 'happy' },
  { id: 'a60', name: 'Sunset Drive', category: 'Travel', icon: '🌇', defaultDuration: 90, defaultMood: 'romantic' },
]

export const CATEGORIES = Array.from(new Set(ACTIVITIES.map(a => a.category))).sort()
export const MOODS = [
  { id: 'happy', label: 'Happy', emoji: '😄' },
  { id: 'relaxed', label: 'Relaxed', emoji: '😌' },
  { id: 'energetic', label: 'Energetic', emoji: '⚡' },
  { id: 'calm', label: 'Calm', emoji: '🧘' },
  { id: 'social', label: 'Social', emoji: '🫂' },
  { id: 'focused', label: 'Focused', emoji: '🎯' },
  { id: 'romantic', label: 'Romantic', emoji: '💞' },
  { id: 'curious', label: 'Curious', emoji: '🔎' },
  { id: 'lazy', label: 'Lazy', emoji: '😴' },
  { id: 'fun', label: 'Fun', emoji: '🎉' },
  { id: 'warm', label: 'Warm', emoji: '🌤️' },
  { id: 'fulfilling', label: 'Fulfilling', emoji: '🌟' },
  { id: 'adventurous', label: 'Adventurous', emoji: '🧭' },
]
